import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Swathi",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/S_logo.ico" style={{ height: 30, width: 30 }} />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
